import type { Supplier, NewsArticle, RiskEvent, MitigationStrategy, SimulationRun } from '@/types';

// ─── Mock Suppliers ────────────────────────────────────────────────────────────
export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: 'sup_001',
    name: 'Rare Earth Mining Co.',
    tier: 3,
    lat: 40.6517,
    lng: 109.8414,
    country: 'China',
    region: 'Baotou, Inner Mongolia',
    categoryExposure: ['geo-political', 'natural disaster', 'regulatory'],
    upstreamIds: [],
    downstreamIds: ['sup_002', 'sup_003'],
    currentRiskScore: 0.72,
    currentImpactScore: 8.1,
    description: 'Primary supplier of rare earth elements critical for smartphone magnets and motors.',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'sup_002',
    name: 'Advanced PCB Ltd.',
    tier: 2,
    lat: 25.0330,
    lng: 121.5654,
    country: 'Taiwan',
    region: 'Taipei, Taiwan',
    categoryExposure: ['geo-political', 'trade policy', 'cyber'],
    upstreamIds: ['sup_001'],
    downstreamIds: ['sup_004'],
    currentRiskScore: 0.65,
    currentImpactScore: 7.4,
    description: 'Advanced printed circuit board and semiconductor substrate manufacturer.',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'sup_003',
    name: 'OLED Display Systems',
    tier: 2,
    lat: 37.5665,
    lng: 126.9780,
    country: 'South Korea',
    region: 'Seoul, South Korea',
    categoryExposure: ['geo-political', 'financial', 'labor'],
    upstreamIds: ['sup_001'],
    downstreamIds: ['sup_004'],
    currentRiskScore: 0.41,
    currentImpactScore: 6.2,
    description: 'World-leading OLED display panel manufacturer for premium smartphones.',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'sup_004',
    name: 'Precision Assembly Corp.',
    tier: 1,
    lat: 22.5431,
    lng: 114.0579,
    country: 'China',
    region: 'Shenzhen, Guangdong',
    categoryExposure: ['labor', 'logistics', 'pandemic/health'],
    upstreamIds: ['sup_002', 'sup_003'],
    downstreamIds: ['sup_005'],
    currentRiskScore: 0.55,
    currentImpactScore: 9.0,
    description: 'Final assembly manufacturer performing device integration and quality control.',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'sup_005',
    name: 'Global Logistics Hub',
    tier: 1,
    lat: 1.3521,
    lng: 103.8198,
    country: 'Singapore',
    region: 'Singapore',
    categoryExposure: ['logistics', 'climate', 'trade policy'],
    upstreamIds: ['sup_004'],
    downstreamIds: [],
    currentRiskScore: 0.30,
    currentImpactScore: 7.8,
    description: 'Regional distribution hub managing final delivery to global markets.',
    createdAt: new Date('2024-01-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
];

// ─── Mock News Articles ────────────────────────────────────────────────────────
export const MOCK_NEWS: NewsArticle[] = [
  {
    id: 'news_001',
    title: 'China Tightens Rare Earth Export Controls Amid Geopolitical Tensions',
    url: 'https://example.com/news/1',
    publishedAt: new Date('2024-01-15T08:00:00Z').toISOString(),
    source: 'Reuters',
    rawContent: 'Beijing has announced new restrictions on rare earth mineral exports, citing national security concerns. The move affects neodymium, dysprosium, and terbium — critical materials for electronics manufacturing.',
    classifiedCategory: 'geo-political',
    affectedGeography: 'China',
    affectedCompany: 'Rare Earth Mining Co.',
    severity: 8,
    processed: true,
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'news_002',
    title: 'Taiwan Strait Military Exercises Disrupt Shipping Lanes',
    url: 'https://example.com/news/2',
    publishedAt: new Date('2024-01-14T12:00:00Z').toISOString(),
    source: 'Bloomberg',
    rawContent: 'Military exercises in the Taiwan Strait have led to temporary rerouting of commercial vessels, causing delays of up to 72 hours for electronics components.',
    classifiedCategory: 'geo-political',
    affectedGeography: 'Taiwan',
    affectedCompany: 'Advanced PCB Ltd.',
    severity: 7,
    processed: true,
    createdAt: new Date('2024-01-14').toISOString(),
  },
  {
    id: 'news_003',
    title: 'Major Cyber Attack Targets Semiconductor Supply Chain Networks',
    url: 'https://example.com/news/3',
    publishedAt: new Date('2024-01-13T06:00:00Z').toISOString(),
    source: 'The Guardian',
    rawContent: 'A sophisticated ransomware attack has compromised supply chain management systems across multiple semiconductor firms in East Asia.',
    classifiedCategory: 'cyber',
    affectedGeography: 'Taiwan, South Korea',
    affectedCompany: 'Advanced PCB Ltd., OLED Display Systems',
    severity: 9,
    processed: true,
    createdAt: new Date('2024-01-13').toISOString(),
  },
  {
    id: 'news_004',
    title: 'Singapore Port Authority Reports Record Congestion Amid Global Trade Surge',
    url: 'https://example.com/news/4',
    publishedAt: new Date('2024-01-12T14:00:00Z').toISOString(),
    source: 'Financial Times',
    rawContent: 'The Port of Singapore is experiencing unprecedented congestion, with vessel waiting times exceeding 5 days. Electronics exporters face delays in final product delivery.',
    classifiedCategory: 'logistics',
    affectedGeography: 'Singapore',
    affectedCompany: 'Global Logistics Hub',
    severity: 6,
    processed: true,
    createdAt: new Date('2024-01-12').toISOString(),
  },
  {
    id: 'news_005',
    title: 'Labor Unrest Grows at Major Electronics Assembly Facilities in Shenzhen',
    url: 'https://example.com/news/5',
    publishedAt: new Date('2024-01-11T09:00:00Z').toISOString(),
    source: 'South China Morning Post',
    rawContent: 'Workers at several electronics assembly plants in Shenzhen have staged work stoppages demanding higher wages and improved conditions. Production has dropped by 30-40%.',
    classifiedCategory: 'labor',
    affectedGeography: 'China',
    affectedCompany: 'Precision Assembly Corp.',
    severity: 7,
    processed: true,
    createdAt: new Date('2024-01-11').toISOString(),
  },
  {
    id: 'news_006',
    title: 'Typhoon Season Threatens South Korean Manufacturing Corridor',
    url: 'https://example.com/news/6',
    publishedAt: new Date('2024-01-10T10:00:00Z').toISOString(),
    source: 'AP News',
    rawContent: 'Meteorologists warn of an active typhoon season that could disrupt manufacturing in the Korean Peninsula. Display panel production facilities are particularly vulnerable.',
    classifiedCategory: 'natural disaster',
    affectedGeography: 'South Korea',
    affectedCompany: 'OLED Display Systems',
    severity: 5,
    processed: true,
    createdAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'news_007',
    title: 'New US Trade Restrictions Target Chinese Semiconductor Supply Chain',
    url: 'https://example.com/news/7',
    publishedAt: new Date('2024-01-09T16:00:00Z').toISOString(),
    source: 'Wall Street Journal',
    rawContent: 'The Biden administration has announced expanded export restrictions targeting advanced semiconductor equipment exports to China, potentially impacting PCB manufacturers dependent on US-sourced tooling.',
    classifiedCategory: 'trade policy',
    affectedGeography: 'China, Taiwan',
    affectedCompany: 'Rare Earth Mining Co., Advanced PCB Ltd.',
    severity: 7,
    processed: true,
    createdAt: new Date('2024-01-09').toISOString(),
  },
  {
    id: 'news_008',
    title: 'Climate Scientists Warn of Increased Flooding Risk in Key Manufacturing Hubs',
    url: 'https://example.com/news/8',
    publishedAt: new Date('2024-01-08T11:00:00Z').toISOString(),
    source: 'Nature',
    rawContent: 'New climate models predict a 40% increase in extreme rainfall events in Southeast Asia by 2025, posing significant risks to manufacturing and logistics infrastructure in the region.',
    classifiedCategory: 'climate',
    affectedGeography: 'Singapore, China',
    affectedCompany: 'Global Logistics Hub, Precision Assembly Corp.',
    severity: 6,
    processed: true,
    createdAt: new Date('2024-01-08').toISOString(),
  },
];

// ─── Mock Risk Events ──────────────────────────────────────────────────────────
export const MOCK_RISK_EVENTS: RiskEvent[] = [
  {
    id: 're_001',
    supplierId: 'sup_001',
    newsArticleId: 'news_001',
    disruptionProbability: 0.72,
    impactScore: 8.1,
    reasoning: 'Export controls directly threaten rare earth supply continuity. Cascades to PCB and OLED production.',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 're_002',
    supplierId: 'sup_002',
    newsArticleId: 'news_002',
    disruptionProbability: 0.65,
    impactScore: 7.4,
    reasoning: 'Taiwan Strait tensions create significant shipping disruption risk for PCB component delivery.',
    createdAt: new Date('2024-01-14').toISOString(),
  },
  {
    id: 're_003',
    supplierId: 'sup_004',
    newsArticleId: 'news_005',
    disruptionProbability: 0.55,
    impactScore: 9.0,
    reasoning: 'Labor unrest at assembly facility directly impacts production capacity at the final assembly stage.',
    createdAt: new Date('2024-01-11').toISOString(),
  },
];

// ─── Mock Mitigations ─────────────────────────────────────────────────────────
export const MOCK_MITIGATIONS: MitigationStrategy[] = [
  {
    id: 'mit_001',
    supplierId: 'sup_001',
    riskEventId: 're_001',
    summary: 'Diversify rare earth sourcing to reduce single-country dependency and build strategic reserves.',
    alternateSuppliers: [
      {
        name: 'Lynas Rare Earths (Australia)',
        location: 'Mount Weld, Western Australia',
        leadTime: '6-8 weeks',
        costPremium: '+15-20%',
        reliability: 'High (98.5% on-time delivery)',
      },
      {
        name: 'MP Materials (USA)',
        location: 'Mountain Pass, California',
        leadTime: '8-10 weeks',
        costPremium: '+25-30%',
        reliability: 'Medium-High (95% on-time delivery)',
      },
    ],
    inventoryAdjustment: [
      {
        action: 'Increase safety stock',
        component: 'Neodymium',
        targetBuffer: '90 days',
        estimatedCost: '$2.3M',
        timeframe: '30 days',
      },
      {
        action: 'Pre-purchase forward contracts',
        component: 'Dysprosium',
        targetBuffer: '60 days',
        estimatedCost: '$1.1M',
        timeframe: '15 days',
      },
    ],
    logisticsRerouting: [
      {
        currentRoute: 'China → Shanghai → Taiwan/Korea',
        alternativeRoute: 'Australia → Singapore → Taiwan/Korea',
        additionalCost: '+$340K/month',
        timeImpact: '+5-7 days transit',
      },
    ],
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'mit_002',
    supplierId: 'sup_004',
    riskEventId: 're_003',
    summary: 'Address labor disputes and diversify assembly capacity to reduce Shenzhen concentration risk.',
    alternateSuppliers: [
      {
        name: 'Vietnam Electronics Assembly (VEA)',
        location: 'Ho Chi Minh City, Vietnam',
        leadTime: '10-12 weeks',
        costPremium: '+8-12%',
        reliability: 'Medium (91% on-time delivery)',
      },
      {
        name: 'Tata Electronics',
        location: 'Tamil Nadu, India',
        leadTime: '14-16 weeks',
        costPremium: '+5-10%',
        reliability: 'Medium-High (94% on-time delivery)',
      },
    ],
    inventoryAdjustment: [
      {
        action: 'Build finished goods buffer',
        component: 'Assembled devices',
        targetBuffer: '45 days',
        estimatedCost: '$8.5M',
        timeframe: '60 days',
      },
    ],
    logisticsRerouting: [
      {
        currentRoute: 'Shenzhen factory → Singapore Hub',
        alternativeRoute: 'Vietnam factory → Bangkok → Singapore Hub',
        additionalCost: '+$120K/month',
        timeImpact: '+3-4 days transit',
      },
    ],
    createdAt: new Date('2024-01-11').toISOString(),
  },
];

// ─── Mock Simulation Runs ──────────────────────────────────────────────────────
export const MOCK_SIMULATION_RUNS: SimulationRun[] = [
  {
    id: 'sim_001',
    scenarioName: 'Taiwan Strait Port Closure',
    scenarioParams: {
      name: 'Taiwan Strait Port Closure',
      description: 'Major port closure due to military escalation in the Taiwan Strait',
      affectedSupplierId: 'sup_002',
      eventType: 'geo-political',
      severity: 9,
      cascadeDepth: 3,
    },
    results: {
      scenario: {
        name: 'Taiwan Strait Port Closure',
        description: 'Major port closure due to military escalation in the Taiwan Strait',
        affectedSupplierId: 'sup_002',
        eventType: 'geo-political',
        severity: 9,
        cascadeDepth: 3,
      },
      affectedSuppliers: [
        { supplier: MOCK_SUPPLIERS[1], newRiskScore: 0.92, newImpactScore: 9.5, cascadeOrder: 0, reasoning: 'Direct impact: PCB facility cut off from shipping lanes' },
        { supplier: MOCK_SUPPLIERS[3], newRiskScore: 0.78, newImpactScore: 8.8, cascadeOrder: 1, reasoning: 'Assembly halted: missing critical PCB components' },
        { supplier: MOCK_SUPPLIERS[4], newRiskScore: 0.61, newImpactScore: 7.2, cascadeOrder: 2, reasoning: 'Distribution delays due to reduced assembly output' },
      ],
      cascadePath: ['sup_002', 'sup_004', 'sup_005'],
      totalImpact: 9.2,
      briefingSummary: 'A Taiwan Strait closure would trigger a cascading disruption across 3 supplier tiers, halting final assembly and causing estimated 6-8 week delivery delays to global markets.',
      mitigations: [],
      responseTimeMs: 2341,
    },
    responseTimeMs: 2341,
    createdAt: new Date('2024-01-16').toISOString(),
  },
];
